# Generated by Django 5.2.1 on 2025-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
